

dados<-data.frame(
  sexo=c("Garoto","Garoto",
         "Garota","Garota","Garota",
         "Garoto","Garota","Garoto","Garota","Garota",
         "Garoto","Garoto","Garoto","Garoto","Garota","Garota",
         "Garoto","Garota","Garoto","Garota","Garoto","Garota",
         "Garota","Garoto","Garoto","Garota","Garota","Garota",
         "Garoto","Garoto","Garoto","Garota","Garoto","Garota",
         "Garoto","Garota","Garota","Garota","Garota","Garota",
         "Garoto","Garota","Garoto","Garota","Garota",
         "Garota","Garota","Garoto","Garota","Garoto","Garota",
         "Garoto","Garota","Garota","Garoto","Garoto","Garoto",
         "Garoto","Garoto","Garoto","Garoto","Garoto",
         "Garoto","Garota","Garoto","Garoto","Garoto","Garoto","Garota","Garoto",
         "Garota","Garoto","Garoto","Garoto","Garota","Garoto","Garota","Garota",
         "Garoto","Garota","Garota","Garota","Garoto","Garoto","Garoto",
         "Garoto","Garoto","Garota","Garota","Garota","Garota","Garoto","Garota",
         "Garota","Garota","Garota","Garota","Garota","Garota","Garota",
         "Garota","Garota","Garoto","Garota","Garoto","Garoto","Garota",
         "Garota","Garota","Garoto","Garota","Garoto","Garota","Garota","Garota",
         "Garoto","Garota","Garoto","Garota","Garoto","Garota","Garoto","Garota","Garota",
         "Garota","Garota","Garota","Garota","Garota","Garota","Garoto",
         "Garota","Garoto","Garoto","Garoto","Garoto","Garoto","Garoto","Garoto",
         "Garota","Garota","Garota","Garoto","Garoto","Garota","Garota","Garoto",
         "Garota","Garoto","Garoto","Garoto","Garota","Garota","Garota",
         "Garota","Garoto","Garoto","Garota","Garoto","Garoto","Garota","Garoto",
         "Garoto","Garoto","Garoto","Garota","Garoto","Garoto","Garota","Garota",
         "Garoto","Garoto","Garoto","Garoto","Garoto","Garota","Garota",
         "Garota","Garota","Garoto","Garoto","Garoto","Garota","Garoto","Garota",
         "Garoto","Garoto","Garoto","Garota"),
  nota_na_primeira_prova =c(91.0,77.5,52.5,
                            54.0,53.5,62.0,59.0,51.5,61.5,
                            56.5,47.5,75.0,47.5,53.5,
                            50.0,50.0,49.0,59.0,60.0,60.0,
                            60.5,50.0,101.0,60.0,60.0,
                            83.5,61.0,75.0,84.0,56.5,56.5,
                            45.0,60.5,77.5,62.5,70.0,
                            69.0,62.0,107.5,54.5,92.5,
                            94.5,65.0,80.0,45.0,45.0,66.0,
                            66.0,57.5,42.5,60.0,64.0,
                            65.0,47.5,57.5,55.0,55.0,76.5,
                            51.5,59.5,59.5,59.5,
                            55.0,70.0,66.5,84.5,57.5,125.0,70.5,
                            79.0,56.0,75.0,57.5,56.0,67.5,114.5,
                            70.0,67.0,60.5,95.0,65.5,85.0,55.0,
                            63.5,61.5,60.0,52.5,65.0,87.5,62.5,
                            66.5,67.0,117.5,47.5,67.5,67.5,77.0,
                            73.5,73.5,68.5,55.0,92.0,55.0,55.0,
                            60.0,120.5,56.0,84.5,60.0,85.0,93.0,
                            60.0,65.0,58.5,85.0,67.0,67.5,65.0,
                            60.0,47.5,79.0,80, 57.5, 64.5, 65, 60, 
                            85, 60, 58, 61.5, 60, 65, 93.5, 52.5, 
                            42.5, 75, 48.5, 64, 66, 82.5, 52.5, 45.5, 
                            57.5, 65, 46, 75, 100, 77.5, 51.5, 62.5, 
                            44.5, 51, 56, 58.5, 69, 65, 60, 65, 65, 
                            40, 55, 52.5, 54.5, 74, 55, 60.5, 50, 48, 
                            51, 55, 93.5, 61, 52.5, 57.5, 60, 71, 65, 
                            60, 55, 60,77.0,52.5,95.0,
                            50.0,47.5,50.0,47.0,71.0,65.0),
  recomendacao_aula_reforco=c("Não",
                              "Não","Não","Não",
                              "Não","Não",
                              "Não","Não","Não","Não","Não","Não","Não",
                              "Não","Não","Não","Não","Não","Não","Não","Não",
                              "Não","Não","Não","Não","Não","Não","Não",
                              "Não","Não","Não","Não","Não","Não","Não",
                              "Não","Não","Não","Não","Não","Não","Não","Não",
                              "Não","Não","Não","Não","Não","Não","Não",
                              "Não","Não","Não","Não","Não","Não","Não",
                              "Não","Não","Não","Não","Não","Não","Não",
                              "Não","Não","Não","Não","Não","Não","Não","Não","Não",
                              "Não","Não","Não","Não","Não","Não","Não","Não","Não","Não",
                              "Não","Não","Não","Não","Não","Não","Não","Não","Não",
                              "Não","Não","Não","Não","Não","Não","Não","Não","Não","Não",
                              "Não","Não","Não","Não","Não","Não","Não","Não","Não",
                              "Não","Não","Não","Não","Não","Não","Não","Não","Não","Não",
                              "Não","Não","Não","Não","Não","Não",
                              "Não","Não","Não","Sim","Sim","Sim","Sim","Sim","Sim",
                              "Sim","Sim","Sim","Sim","Sim","Sim","Sim","Sim",
                              "Sim","Sim","Sim","Sim","Sim","Sim","Sim","Sim",
                              "Sim","Sim","Sim","Sim","Sim","Sim","Sim","Sim",
                              "Sim","Sim","Sim","Sim","Sim","Sim","Sim","Sim",
                              "Sim","Sim","Sim","Sim","Sim","Sim","Sim","Sim",
                              "Sim","Sim","Sim","Sim","Sim","Sim",
                              "Sim","Sim","Sim","Sim","Sim","Sim","Sim"))
